Litcrique-2/website/views.py
from flask import Blueprint,render_template,request, flash, redirect, url_for,g
from flask_login import login_user, login_required, logout_user, current_user
import sqlite3
from django.shortcuts import render, redirect
from .models import Book, Review
import os
from flask_paginate import Pagination, get_page_parameter
import math




views = Blueprint('views', __name__)


DATABASE = '/home/harshdeep/Desktop/LitCritique/instance/LITCRITQUE.db'

@views.route('/home')
def home():
    return render_template('home.html',user = current_user)
    

@views.route('/community')
def community():
    return render_template('community.html',user = current_user)
    

@views.route('/trending')
def trending():
    return 'Trending book of the books!'



@views.route('/contactus')
def contactus():
    return render_template('contactus.html',user = current_user)




@views.route('/supportus')
def supportus():
    return render_template('supportus.html',user = current_user)


@views.route('/', methods=["GET", "POST"])
def search():
    if request.method == "POST":
        search_query = request.form["search_query"]
        results = Book.query.filter(Book.title.like('%' + search_query + '%')).all()
        return render_template("search_books.html", results=results, user=current_user)
    return render_template("home.html", user=current_user)

@views.route('/book/<title>')
def book(title):
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT book.title, book.authors, book.image, book.previewLink,
               book.description, book.rating, book.publisher, book.Categories
        FROM book
        WHERE book.title = ?
    """, (title,))    
    book = cursor.fetchone()
    if book is None:
        #flash("Book not found.")
        return redirect(url_for("views.home"))
    # Get the reviews for the book
    cursor.execute("""
        SELECT review_summary, review_text, rating_user, user_name
        FROM review
        WHERE book_title = ?
    """, (title,))
    reviews = cursor.fetchall()
    return render_template("book_details.html",book_title=book[0], book_author=book[1], book_image=book[2], book_preview=book[3], book_description=book[4], book_rating=book[5], book_publisher=book[6], book_categories=book[7], user=current_user, reviews=reviews)

@views.route('/book/<title>/add_review', methods=['POST','GET'])
@login_required
def add_review(title):
    rating_user = int(request.form['rating_user'])
    review_summary = request.form['review_summary']
    review_text = request.form['review_text']
    user_name = current_user.user_name
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO review (book_title, user_name, rating_user, review_summary, review_text)
        VALUES (?, ?, ?, ?, ?)
    """, (title, user_name, rating_user, review_summary, review_text))
    conn.commit()
    conn.close()
    return redirect(url_for('views.book', title=title))




@views.route('/category/<category>')
def category(category):
    per_page = 100
    page = request.args.get('page', 1, type=int)
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT book.title, book.authors, book.image, book.previewLink,
               book.description, book.rating, book.publisher, book.Categories
        FROM book
        WHERE book.Categories LIKE ?
    """, ('%' + category + '%',))
    books = cursor.fetchall()
    if not books:
        flash("No books found in this category.")
        return redirect(url_for("views.home"))
    total_pages = math.ceil(len(books) / per_page)
    pagination = Pagination(page=page, per_page=per_page, total=len(books), css_framework="bootstrap4")
    start = (page - 1) * per_page
    end = start + per_page
    books = books[start:end]
    return render_template("category.html", category=category, books=books, pagination=pagination, user=current_user, total_pages=total_pages , page=page)



@views.route("/categories")
def categories():
    per_page = 100
    page = request.args.get('page', 1, type=int)
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    
    query = request.args.get('query')
    if query:
        cursor.execute("""
            SELECT DISTINCT Categories
            FROM book
            WHERE Categories IS NOT NULL AND Categories LIKE ?
        """, ('%' + query + '%',))
    else:
        cursor.execute("""
            SELECT DISTINCT Categories
            FROM book
            WHERE Categories IS NOT NULL
        """)
    
    categories = [category[0] for category in cursor.fetchall()]
    categories.sort()
    total_pages = math.ceil(len(categories) / per_page)
    pagination = Pagination(page=page, per_page=per_page, total=len(categories), css_framework="bootstrap4")
    start = (page - 1) * per_page
    end = start + per_page
    categories = categories[start:end]
    return render_template("categories.html", categories=categories, pagination=pagination, user=current_user, total_pages=total_pages , page=page)


@views.route('/author/<author>')
def author(author):
    per_page = 100
    page = request.args.get('page', 1, type=int)
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT book.title, book.authors, book.image, book.previewLink,
               book.description, book.rating, book.publisher, book.Categories
        FROM book
        WHERE book.authors LIKE ?
    """, ('%' + author + '%',))
    books = cursor.fetchall()
    if not books:
        flash("No books found by this Author.")
        return redirect(url_for("views.home"))
    total_pages = math.ceil(len(books) / per_page)
    pagination = Pagination(page=page, per_page=per_page, total=len(books), css_framework="bootstrap4")
    start = (page - 1) * per_page
    end = start + per_page
    books = books[start:end]
    return render_template("author.html", author = author, books=books, pagination=pagination, user=current_user, total_pages=total_pages , page=page)



@views.route("/authors")
def authorss():
    per_page = 100
    page = request.args.get('page', 1, type=int)
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    
    query = request.args.get('query')
    if query:
        cursor.execute("""
            SELECT DISTINCT authors
            FROM book
            WHERE authors IS NOT NULL AND authors LIKE ?
        """, ('%' + query + '%',))
    else:
        cursor.execute("""
            SELECT DISTINCT authors
            FROM book
            WHERE authors IS NOT NULL
        """)
    
    authors = [author[0] for author in cursor.fetchall()]
    authors.sort()
    total_pages = math.ceil(len(authors) / per_page)
    pagination = Pagination(page=page, per_page=per_page, total=len(authors), css_framework="bootstrap4")
    start = (page - 1) * per_page
    end = start + per_page
    authors = authors[start:end]
    return render_template("authors.html", authors=authors, pagination=pagination, user=current_user, total_pages=total_pages , page=page)



@views.route('/userprofile')
@login_required
def userprofile():
    return render_template('userprofile.html',user = current_user)

@views.route('/add_to_reading_list/<int:book_id>')
@login_required
def add_to_reading_list(book_id):
    book = Book.query.get(book_id)
    current_user.reading_list.append(book)
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    conn.commit()
    conn.close()
    flash('Book added to reading list.')
    return redirect(url_for('book_details', book_id=book.index))



@views.route('/treanding')
def treanding():
    categories = ['Fiction', 'ART', 'Religion','Psychology', 'Biography & Autobiography', 'Cooking', 'Political Science', 'Technology & Engineering', 'History', 'Humor']
    
    books = []
    conn = sqlite3.connect(DATABASE)

    cursor = conn.cursor()
    for category in categories:
        
        category_books = cursor.execute("""
            SELECT book.id, book.title, book.authors, book.rating, book.image
            FROM book
            JOIN review ON book.title = review.book_title
            WHERE book.Categories = ?
            GROUP BY book.id
            ORDER BY COUNT(review.id) DESC
            LIMIT 5
        """, (category,)).fetchall()
        books.append((category, category_books))
    
    conn.close()
    return render_template('treanding.html', books=books, user=current_user)

@views.route('/books')
def books():
    per_page = 150
    page = request.args.get('page', 1, type=int)
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()
    
    query = request.args.get('query')
    if query:
        cursor.execute("""
            SELECT id, title, authors, rating, image
            FROM book
            WHERE title IS NOT NULL AND title LIKE ?
        """, ('%' + query + '%',))
    else:
        cursor.execute("""
            SELECT id, title, authors, rating, image
            FROM book
            WHERE title IS NOT NULL
        """)
    
    books = cursor.fetchall()
    books.sort()
    total_pages = math.ceil(len(books) / per_page)
    pagination = Pagination(page=page, per_page=per_page, total=len(books), css_framework="bootstrap4")
    start = (page - 1) * per_page
    end = start + per_page
    books = books[start:end]
    return render_template("books.html", books=books , pagination=pagination, user=current_user, total_pages=total_pages , page=page)

Litcrique-2/website/templates/author.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <h2 class="mb-4">Books by {{ author }}</h2>
    <div class="row">
        {% for book in books %}
        <div class="col-md-4">
            <a href="{{ url_for('views.book', title=book[0]) }}" class="book-link">
                <img src="{{ book[2] }}" alt="{{ book[0] }}" class="book-image">
            </a>
            <div class="book-info">
                <h2 class="book-title">{{ book[0] }}</h2>
                
                <div class="book-rating">
                    <div class="current-rating d-inline-flex align-items-center">
                        {% for i in range(book[5]) %}
                            <span class="fa fa-star checked" style="font-size: 24px;"></span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-4">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.author', author = author, page=pagination.prev_num) }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            {% endif %}
    
            {% if pagination.page > 3 %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.author', author=author, page=1) }}">1</a>
            </li>
            {% endif %}
    
            {% if pagination.page > 4 %}
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
            {% endif %}
    
            {% for num in pagination.pages %}
                {% if num %}
                    {% if num == pagination.page %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('views.author', author=author, page=num) }}">{{ num }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
    
    
            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.author', author=author, page=pagination.next_num) }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
            {% endif %}
        </ul>
    </nav>
    

</div>

{% endblock %}

Litcrique-2/website/templates/book.html
<div class="book">
    <img src="{{ book_image }}" alt="{{ book_title }}">
    <div class="book-info">
      <h2>{{ book_title }} by {{ book_author }}</h2>
      <p class="rating">{{ book_rating }} stars</p>
    </div>
  </div>
  

Litcrique-2/website/templates/book_details.html
{% extends 'base.html' %}

{% block content %}

<script>
  function fillStar(star) {
    var rating = star.id.slice(-1);
    document.getElementById("rating_user").value = rating;
    for (var i = 1; i <= 5; i++) {
      var s = document.getElementById("star" + i);
      if (i <= rating) {
        s.classList.remove("fa-star-o");
        s.classList.add("fa-star");
      } else {
        s.classList.remove("fa-star");
        s.classList.add("fa-star-o");
      }
    }
  }
</script>


      <div class="container my-5">
        <div class="row">
          <div class="col-md-4">
            <a href="{{book_preview}}" target="_blank">
              <img src="{{book_image}}" alt="Book Cover" class="img-fluid mb-3">
            </a>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <div>
                  <span class="me-2">Rate this book:</span>
                  <span class="fa fa-star-o checked" onclick="fillStar(this)"></span>
                  <span class="fa fa-star-o checked" onclick="fillStar(this)"></span>
                  <span class="fa fa-star-o checked" onclick="fillStar(this)"></span>
                  <span class="fa fa-star-o" onclick="fillStar(this)"></span>
                  <span class="fa fa-star-o" onclick="fillStar(this)"></span>
                </div>
              </div>
              
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-dark">Add to Reading List</button>
              </div>
          </div>
          <div class="col-md-8">
            <h1>{{book_title}}</h1>
            <h3>by <a href="https://www.google.com/search?q={{book_author}}" target="_blank" >{{book_author}}</a>
              <div class="current-rating d-inline-flex align-items-center">
                {% for i in range(book_rating) %}
                    <span class="fa fa-star checked" style="font-size: 24px;"></span>
                {% endfor %}
              </div>
              
          
            </h3>
            <h3>{{book_categories}}</h3>
            <h4>Book Description</h4>
            <p>{{book_description}}</p>
            <h4>Book Details</h4>
            <ul>
              <li><strong>Author:</strong> {{book_author}}</li>
              <li><strong>ISBN:</strong> 978-1234567890</li>
              <li><strong>Publisher:</strong> {{book_pulisher}}</li>
            </ul>
          </div>
        </div>
      
      

        <div class="row mt-5">
          <div class="col-md-12">
            <h2>Reviews and Ratings</h2>
            <hr>
            {% for review in reviews %}
            <div class="row">
              <div class="col-md-2 mb-3">
                <img src="https://via.placeholder.com/100" alt="User Image" class="img-fluid rounded-circle">
                <p class="mt-2 mb-0"><strong>{{ review[3] }}</strong></p>
                <div class="current-rating d-inline-flex align-items-center">
                  {% for i in range(review[2]) %}
                    <span class="fa fa-star checked" style="font-size: 24px;"></span>
                  {% endfor %}
                </div>
              </div>
              <div class="col-md-10 mb-3">
                <h4>{{ review[0] }}</h4>
                <p>{{ review[1] }}</p>
                <hr>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        
        <div class="row mt-5">
          <div class="col-md-12">
            <h2>Rate this book!!</h2>
            <hr>
            {% if current_user.is_authenticated %}
            <form method="POST" action="{{ url_for('views.add_review', title=book_title) }}">
              <div class="mb-3">
                <label for="rating_user" class="form-label">Your Rating:</label>
                <div>
                  <span class="fa fa-star-o checked" onclick="fillStar(this)" id="star1"></span>
                  <span class="fa fa-star-o checked" onclick="fillStar(this)" id="star2"></span>
                  <span class="fa fa-star-o checked" onclick="fillStar(this)" id="star3"></span>
                  <span class="fa fa-star-o" onclick="fillStar(this)" id="star4"></span>
                  <span class="fa fa-star-o" onclick="fillStar(this)" id="star5"></span>
                  <input type="hidden" name="rating_user" id="rating_user" value="0">
                </div>
              </div>
              <div class="mb-3">
                <label for="review_summary" class="form-label">Review Summary:</label>
                <input type="text" class="form-control" name="review_summary" id="review_summary">
              </div>
              <div class="mb-3">
                <label for="review_text" class="form-label">Review Text:</label>
                <textarea class="form-control" name="review_text" id="review_text" rows="5"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit Review</button>
            </form>
            {% endif %}
          </div>
        </div>

      </div>
      

{% endblock %}

Litcrique-2/website/templates/books.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5"></divclass>
    <h1>All Books</h1>
    <form action="{{ url_for('views.books') }}" method="GET">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Search books" name="query" value="{{ request.args.get('query', '') }}">
            <div class="input-group-append">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </div>
    </form>

    {% if books %}
        <div class="row">
            {% for book in books %}
            <div class="col-md-3">
                <div class="book-card">
                  <a href="{{ url_for('views.book', title=book[1]) }}" class="book-link">
                    <img src="{{ book[4] }}" alt="{{ book[1] }}" class="book-image">
                  </a>
                  <div class="book-info">
                    <h2 class="book-title">{{ book[1] }}</h2>
                    <p class="book-author">By {{ book[2] }}</p>
                    <div class="book-rating">
                      <div class="current-rating d-inline-flex align-items-center">
                        {% for i in range(book[3]) %}
                            <span class="fa fa-star checked" style="font-size: 24px;"></span>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                {% if loop.index % 4 == 0 %}
                    </div><div class="row">
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>No Book found.</p>
    {% endif %}
    

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-4">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.books', books=books, page=pagination.prev_num) }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            {% endif %}

    
            {% if pagination.page > 4 %}
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
            {% endif %}
    
            {% for num in pagination.pages %}
                {% if num %}
                    {% if num == pagination.page %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('views.books', books=books, page=num) }}">{{ num }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
    
    
            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.books', books=books, page=pagination.next_num) }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
            {% endif %}
        </ul>
    </nav>

    </div>
{% endblock %}

Litcrique-2/website/templates/categories.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5"></divclass>
    <h1>All Categories</h1>
    <form action="{{ url_for('views.categories') }}" method="GET">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Search Categories" name="query" value="{{ request.args.get('query', '') }}">
            <div class="input-group-append">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </div>
    </form>

    {% if categories %}
        <div class="row">
            {% for category in categories %}
                <div class="col-md-3 mb-3">
                    <a href="{{ url_for('views.category', category=category) }}" class="btn btn-dark btn-block text-light">{{ category }}</a>
                </div>
                {% if loop.index % 4 == 0 %}
                    </div><div class="row">
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>No categories found.</p>
    {% endif %}
    

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-4">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.categories', categories=categories, page=pagination.prev_num) }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            {% endif %}

    
            {% if pagination.page > 4 %}
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
            {% endif %}
    
            {% for num in pagination.pages %}
                {% if num %}
                    {% if num == pagination.page %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('views.categories', categories=categories, page=num) }}">{{ num }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
    
    
            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.categories', categories=categories, page=pagination.next_num) }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
            {% endif %}
        </ul>
    </nav>

    </div>
{% endblock %}

Litcrique-2/website/templates/category.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <h2 class="mb-4">Books in {{ category }}</h2>
    <div class="row">
        {% for book in books %}
        <div class="col-md-4">
            <a href="{{ url_for('views.book', title=book[0]) }}" class="book-link">
                <img src="{{ book[2] }}" alt="{{ book[0] }}" class="book-image">
            </a>
            <div class="book-info">
                <h2 class="book-title">{{ book[0] }}</h2>
                <p class="book-author">By {{ book[1] }}</p>
                <div class="book-rating">
                    <div class="current-rating d-inline-flex align-items-center">
                        {% for i in range(book[5]) %}
                            <span class="fa fa-star checked" style="font-size: 24px;"></span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-4">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.category', category=category, page=pagination.prev_num) }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            {% endif %}
    
            {% if pagination.page > 3 %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.category', category=category, page=1) }}">1</a>
            </li>
            {% endif %}
    
            {% if pagination.page > 4 %}
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
            {% endif %}
    
            {% for num in pagination.pages %}
                {% if num %}
                    {% if num == pagination.page %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('views.category', category=category, page=num) }}">{{ num }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
    
    
            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('views.category', category=category, page=pagination.next_num) }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
            {% endif %}
        </ul>
    </nav>
    

</div>

{% endblock %}

Litcrique-2/website/templates/community.html
{% extends 'base.html' %}


{% block content %}
   

      <div class="container my-4 mb-4">
        <div class="row">
          <div class="col-md-6">  
            <div class="discussion-links">
                <h2>Discussion Links</h2>
                <ul class="link-list">
                    <li><a href="#" class="link">Discussion Link 1 Bla Bla</a></li>
                    <li><a href="#" class="link">Discussion Link 2 Bla</a></li>
                    <li><a href="#" class="link">Discussion Link 3 Bla Bla</a></li>
                    <li><a href="#" class="link">Discussion Link 4 BLa Bla</a></li>
                    <li><a href="#" class="link">Discussion Link 5 Bla Bla</a></li>
                    <li><a href="#" class="link">Discussion Link 6 Bla Bla</a></li>
                </ul>
                </div>
          </div>       
          <div class="col-md-6">
            <div class="post-discussion">
              <h2>Post a Discussion</h2>
              <form>
                <label for="title">Title:</label>
                <input type="text" id="title" name="title"><br><br>
                <label for="message">Message:</label><br>
                <textarea id="message" name="message" rows="10" cols="50"></textarea><br><br>
                <input type="submit" value="Post Discussion">
              </form>
            </div>
          </div>
        </div>
      </div>
      


{% endblock %}

Litcrique-2/website/templates/contactus.html
{% extends 'base.html' %}




{% block content %}

      <div class="container" style="margin-top: 50px;">
        <h1>Contact Us</h1>
        <hr>
        <h3>Office Address</h3>
        <p>WC -09 Girnar House IIT Delhi</p>
        <h3>General Enquiries</h3>
        <p>Email: info@litcritique.com</p>
        <h3>Review Requests</h3>
        <p>Email: reviews@litcritique.com</p>
        <h3>Advertising Enquiries</h3>
        <p>Email: advertising@litcritique.com</p>
        
        <h3>Phone Number</h3>
        <p>+91 7206217237</p>
        <h3>Fax Number</h3>
        <p>555-123-4567</p>
        <h3>Hours of Operation</h3>
        <p>Monday-Friday: 9am-5pm</p>
        <h3>Social Media Handles</h3>
        <ul>
          <li><a href="https://twitter.com/" target="_blank">Twitter</a></li>
          <li><a href="https://www.facebook.com/" target="_blank">Facebook</a></li>
          <li><a href="https://www.instagram.com/" target="_blank">Instagram</a></li>
        </ul>
      </div>
      

{% endblock %}

Litcrique-2/website/templates/macros.html
{% macro len(item) %}
    {{ item|length }}
{% endmacro %}

Litcrique-2/website/templates/riught.html
{% extends "base.html" %}

{% block content %}
 
{% if pagination.pages > 1 %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if pagination.has_prev %}
    <li class="page-item"><a class="page-link" href="{{ url_for('views.category', category=category, page=pagination.prev_num) }}">Previous</a></li>
    {% endif %}
    {% for page in pagination.iter_pages() %}
    {% if page %}
    {% if page == pagination.page %}
    <li class="page-item active"><span class="page-link">{{ page }}</span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{ url_for('views.category', category=category, page=page) }}">{{ page }}</a></li>
    {% endif %}
    {% else %}
    <li class="page-item disabled"><span class="page-link">...</span></li>
    {% endif %}
    {% endfor %}
    {% if pagination.has_next %}
    <li class="page-item"><a class="page-link" href="{{ url_for('views.category', category=category, page=pagination.next_num) }}">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}